GET http://localhost:3003/api/blogs/6882c2fd01e2c5dc1ea7d36b
###
DELETE http://localhost:3003/api/blogs/6882c2fd01e2c5dc1ea7d36b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hbW1hIiwiaWQiOiI2ODgyMGZjZDQzMzc5ZGYzNmMxZTUxMTQiLCJpYXQiOjE3NTM0NTEzMDV9.IHD2P9a1KpWozAfZzGUUQMEeYqqfcnY-mgCUHzfBfNw
###
POST http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hbW1hIiwiaWQiOiI2ODgyMGZjZDQzMzc5ZGYzNmMxZTUxMTQiLCJpYXQiOjE3NTM0NTEzMDV9.IHD2P9a1KpWozAfZzGUUQMEeYqqfcnY-mgCUHzfBfNw
Content-Type: application/json

{
    "title": "NATASJHA",
    "author": "HERE",
    "url": "http://somesite.com/bradpitt",
    "likes": 2
}
###
PUT http://localhost:3003/api/blogs/68134786cb9fc669cbca9684
Content-Type: application/json

{
    "likes": 99
}
###
GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username":"mamma",
    "name":"Mich",
    "password":"mamma"
}
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username":"mamma",
    "password":"mamma"
}