GET http://localhost:3003/api/blogs/
###
DELETE http://localhost:3003/api/blogs/6880b5fc8acb36fa7c73a6e6
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "giggano",
    "author": "shis",
    "url": "http://somesite.com/bradpitt",
    "likes": 2
}
###
PUT http://localhost:3003/api/blogs/68134786cb9fc669cbca9684
Content-Type: application/json

{
    "likes": 99
}
###
GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username":"ssslksx",
    "name":"Mich",
    "password":"se"
}