GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/680bc505812880656af1ef25
###
DELETE http://localhost:3001/api/persons/680bc505812880656af1ef25
###
POST http://localhost:3001/api/persons
content-type: application/json
//nigga

{
    "name": "nnssjss",
    "number": "123 456 789"
}